### ISSUE TITLE
Suggestion - Improvements 

### ISSUE THREAD

**Issue by Pr0xy671** [haigiang02/the-silencer#1]
Line 78, replace with: def _send_http_post(self, pause=random.randint(5,10)): 

Line 85, modify to: "Keep-Alive: %s\r\n" 

Line 88, modify to: (self.host, random.choice(useragents), random.randint(300, 894)))
****CHANGE THE VALUE OF KEEP-ALIVE TIMES TO FIT YOUR NEEDS/WANTS****

Line 106, change "9050" to: 9150

**Comment by haigiang02** [comment]
Thanks for the error spotting! I am working on it now

**Comment by Pr0xy671** [comment]
[Silencer.txt](https://github.com/haigiang02/the-silencer/files/95766/Silencer.txt)

Read the text document I uploaded. I added cookies for firewall problem, add HTTP GET request, etc.

**Comment by haigiang02** [comment]
Thanks! 
When did you start working with python? You seem like a pretty professional guy!

**Comment by haigiang02** [comment]
Also, you suggested to add a GET as well. However, it is shown that GET is not as efficient as POST for stressing a server.
What do you think?

**Comment by haigiang02** [comment]
Oh I see the get is to be random. My bad

**Comment by haigiang02** [comment]
For the check host down, I am trying to do that by myself by using isup.me/site.com
Then search for string "down", and using that to detect.

**Comment by haigiang02** [comment]
Also, you can directly edit the files by clicking the file, and then click the little pen symbol on the top right of the coding screen

**Comment by Pr0xy671** [comment]
Hello, 
I'm still learning Python, but I will become good at it someday haha. I just look at other Python (D)DoS and I add whatever is useful. 
Also, I didn't know about the edit files directly. I don't know how to use Github. 
I will try and improve performance so it uses less CPU, but I need you to test it because I have no way to tell how much CPU power a script uses on my computer.

**Comment by Pr0xy671** [comment]
I tried the pen symbol on the top right, but if I click on it, it will make me fork your project. Is there a way where I just edit the code directly?

**Comment by Pr0xy671** [comment]
[Silence.zip](https://github.com/haigiang02/the-silencer/files/96477/Silence.zip)
I copied your code and worked on it a little. I made it more random, added HTTP HEAD request, etc. 
I also tried to make the code shorter and smaller because I think that if there is less code, then there is less memory consumption of CPU (idk, it made sense in my head).

**Comment by haigiang02** [comment]
Thanks! You can fork it, and then do a pull request

**Comment by Pr0xy671** [comment]
Hey @haigiang02 
Do you have Threema? We can discuss, collaborate and help each other out for future projects.

**Comment by haigiang02** [comment]
Sadly, I don't.
How about just emailing?
protonmail.ch offers the same/more protection than threema

**Comment by Pr0xy671** [comment]
I'll create an account tomorrow, it's night time here and I have school
tomorrow, I'll let you know once I create one.
Also, do you happen to have a server/site where we can test DoS tools and
you can see the HTTP requests?

**Comment by haigiang02** [comment]
For testing,  an option is getting a droplet on DigitalOcean ($5/month for the cheapest VPS) and setting up a dummy apache server. You can test it on many hosts as well, but be sure to contact support, since sometimes taking down a VPS/Server will affect other servers as well, which is not allowed.
Temporarily, just drop me an email at sadaroc11@protonmail.ch and I will respond since it does take a while to get approved into protonmail.

**Comment by Pr0xy671** [comment]
I sent you an email. 
Also, how do you put codes/script into GitHub?

**Comment by Pr0xy671** [comment]
https://github.com/whitepacket/Stinger-Tor/blob/master/stinger.py
This could be useful for silencer, the author claims "can't be filtered by anti-DoS systems".

**Comment by haigiang02** [comment]
Thanks, will look into it

On Fri, Jan 22, 2016 at 6:07 PM, Pr0xy671 <notifications@github.com> wrote:

> https://github.com/whitepacket/Stinger-Tor/blob/master/stinger.py
> This could be useful for silencer, the author claims "can't be filtered by
> anti-DoS systems".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haigiang02/the-silencer/issues/1#issuecomment-173881375>
> .
>



-- 
Sincerely
Giang Nguyen

My tech blog: http://zunzutech.com/blog
My tech forum: http://zunzutech.com/forum
